# Manually defined class structure
MANUAL_CLASSES = {'shirt':['clothing'],
'sweater':['clothing'],
'sock':['clothing'],
'underpants':['clothing'],
'shoe':['clothing'],
'jacket':['clothing'],
'jeans':['clothing'],
'hat':['clothing'],
'scarf':['clothing'],
'trousers':['clothing'],
'T-shirt':['clothing'],
'coat':['clothing'],
'skirt':['clothing'],
'dress':['clothing'],
'shorts':['clothing'],
'blouse':['clothing'],
'belt':['clothing'],
'tie':['clothing'],
'bra':['clothing'],
'swimsuit':['clothing'],
'meat':['food'],
'yoghurt':['food'],
'milk':['food'],
'salad':['food'],
'tomatoe':['food'],
'strawberry':['food'],
'blueberry':['food'],
'banana':['food'],
'broccoli':['food'],
'bacon':['food'],
'rice':['food'],
'carrot':['food'],
'corn':['food'],
'chocolate':['food'],
'chili':['food'],
'apple':['food'],
'cucumber':['food'],
'beans':['food'],
'jam':['food'],
'noodles':['food'],
'onion':['food'],
'olive':['food'],
'raisin':['food'],
'salmon':['food'],
'spaghetti':['food'],
'spinach':['food'],
'syrup':['food'],
'tofu':['food'],
'tuna':['food'],
'vinegar':['food'],
'watermelon':['food'],
'sugar':['food'],
'salt':['food'],
'pepper':['food'],
'bread':['food'],
'orange':['food'],
'mustard':['food'],
'lemonade':['food'],
'water':['food'],
'cheese':['food'],
'garlic':['food'],
'egg':['food'],
'cherry':['food'],
'cinnamon':['food'],
'butter':['food'],
'avocado':['food'],
'spoon':['kitchen utensils'],
'fork':['kitchen utensils'],
'knife':['kitchen utensils'],
'plate':['kitchen utensils'],
'cup':['kitchen utensils'],
'pot':['kitchen utensils'],
'kettle':['kitchen utensils'],
'pan':['kitchen utensils'],
'blender':['kitchen utensils'],
'mug':['kitchen utensils'],
'bowl':['kitchen utensils'],
'grater':['kitchen utensils'],
'spatula':['kitchen utensils'],
'peeler':['kitchen utensils'],
'whisk':['kitchen utensils'],
'tray':['kitchen utensils'],
'cutting board':['kitchen utensils'],
'corkscrew':['kitchen utensils'],
'mits':['kitchen utensils'],
'frying pan':['kitchen utensils'],
'ladle':['kitchen utensils'],
'picture':['accessoires'],
'book':['accessoires'],
'computer':['accessoires'],
'plant':['accessoires'],
'table lamp':['accessoires'],
'candle':['accessoires'],
'television':['accessoires'],
'vase':['accessoires'],
'floor lamp':['accessoires'],
'carpet':['accessoires'],
'clock':['accessoires'],
'pillow':['accessoires'],
'speakers':['accessoires'],
'newspaper':['accessoires'],
'magazine':['accessoires'],
'teddy':['accessoires'],
'gel':['accessoires'],
'duvet':['accessoires'],
'eyeliner':['accessoires'],
'perfume':['accessoires'],
'lipstick':['accessoires'],
'phone':['accessoires'],
'radio':['accessoires'],
'monitor':['accessoires'],
'food':['entity'],
'clothing':['entity'],
'kitchen utensils': ['entity'],
'accessoires': ['entity']
}